version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: game-db
    environment:
      POSTGRES_DB: nakama
      POSTGRES_USER: nakama
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/nakama/data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nakama:
    image: heroiclabs/nakama:latest
    container_name: game-nakama
    depends_on:
      - postgres
    environment:
      NAKAMA_DATABASE_HOST: postgres
      NAKAMA_DATABASE_USER: nakama
      NAKAMA_DATABASE_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/nakama/modules:/nakama/data/modules
      - ./docker/nakama/data/nakama:/nakama/data
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"